### ISSUE TITLE
My computer didn't have the path and file “C:\Users\younger\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1”

### ISSUE THREAD

**Issue by younger-1** [liuzijing97/scoop-auto-completion#12]
All the things are right at first
```
PS C:\Users\younger> $env:SCOOP
C:\Users\younger\scoop
PS C:\Users\younger> $env:USERPROFILE
C:\Users\younger
PS C:\Users\younger> Import-Module "$env:SCOOP/modules/scoop-completion"
```
For `enable completion in current shell`  it works

but it fails to `enable auto-load` 
```
PS C:\Users\younger> Add-Content -Path $Profile -Value "`nImport-Module `"$env:SCOOP/modules/scoop-completion`""
Add-Content : 未能找到路径“C:\Users\younger\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1”的一部分。
所在位置 行:1 字符: 1
+ Add-Content -Path $Profile -Value "`nImport-Module `"$env:SCOOP/modul ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\younge...ell_profile.ps1:String) [Add-Content], DirectoryNotF
   oundException
    + FullyQualifiedErrorId : GetContentWriterDirectoryNotFoundError,Microsoft.PowerShell.Commands.AddContentCommand
```
I didn't find the path and the file in my computer,so I think it may be PowerShell' config, but I don't know why

**Comment by Moeologist** [comment]
exec
```powershell
New-Item -Path $profile -ItemType "file" -Force
```
before Add-Content

**Comment by younger-1** [comment]
> exec
> 
> ```powershell
> New-Item -Path $profile -ItemType "file" -Force
> ```
> 
> before Add-Content

Thanks.

**Comment by Cry0nicS** [comment]
@Moeologist please add the _force_ commend to the homepage too.

**Comment by Moeologist** [comment]
@Cry0nicS Thank you for the advice.I will do it.

**Comment by Lockszmith-GH** [comment]
I would recommend instead of using ``$profile`` use ``$profile.CurrentUserAllHosts``, this way it will be available not only in the Windows supplied console, but in ISE and any other PowerShell host (think vscode, etc..).
If you want it machine wide, and not just for the current user, use ``$profile.AllUserAllHosts``

**Comment by Moeologist** [comment]
Thx, I will add this to README.

**Comment by younger-1** [comment]
> I would recommend instead of using `$profile` use `$profile.CurrentUserAllHosts`, this way it will be available not only in the Windows supplied console, but in ISE and any other PowerShell host (think vscode, etc..).
> If you want it machine wide, and not just for the current user, use `$profile.AllUserAllHosts`

Using `$profile` setting only, it can still work in powershell of VScode, cmder and winTerminal etc...
But not working in ISE. So I don't know what's more the setting you said above can do. Maybe I am misunderstanding...
