### ISSUE TITLE
能提供卸载说明吗？

### ISSUE THREAD

**Issue by mephisX** [liuzijing97/scoop-auto-completion#14]
![image](https://user-images.githubusercontent.com/30206556/69770955-ecf61080-11c5-11ea-9294-3e964dab1ddc.png)
现在打开都是这个样子了。

**Comment by Moeologist** [comment]
可以文本编辑器打开Microsoft.Powershell_profile.ps1，删除其中的Import-module 行

**Comment by Moeologist** [comment]
是scoop uninstall 之后报错吗。还是按照安装说明就有问题。
不再需要这个模块，可以同时删除bucket
```powershell
scoop bucket rm scoop-completion
```

**Comment by mephisX** [comment]
安装没问题，卸载有问题。
主要是安装了不知道有什么用 scoop 的命令都很短。
自动补全的时候感觉还没自己输入得快。
如果你能分享使用方法那就更好了！

**Comment by Moeologist** [comment]
在所有子命令都熟知的情况下，命令补全确是没有用途。最常见的是用来补全包名
```
scoop install q
```
按tab或ctrl-space，可以补全q开头的包名，因为记住所有包名可能很难。补全项几乎覆盖了所有可能的scoop输入，命令参数、本地包、远程包、bucket、alias等等。
这对于习惯使用Unix shell补全的用户可能很自然。但如果熟知这些，补全可能依然在浪费时间。
已经修改了安装说明，去除了自动修改$profile的命令，我在考虑怎么写上更形象的用法说明。
