### ISSUE TITLE
Suggestion: support completion with sudo

### ISSUE THREAD

**Issue by Lockszmith-GH** [liuzijing97/scoop-auto-completion#16]
Currently if the scoop command is prefixed with the `sudo` command, the completion breaks.
I wonder if it would be possible to modify completion so that `sudo scoop` would work.

**Comment by Lockszmith-GH** [comment]
Adding background, in case you don't use the `sudo` command.
Install it with `scoop install sudo`.
I actually install it as a `--global` package.

The way I use it with scoop is for `--global` installation, which require elevation, for example:
`sudo scoop install --global git`

**Comment by Moeologist** [comment]
It will be implemented in next version.
