### ISSUE TITLE
support `Register-ArgumentCompleter` mode

### ISSUE THREAD

**Issue by Cologler** [liuzijing97/scoop-auto-completion#22]
To resolve growing PowerShell completion modules, I write a lazy loader module to load them: https://github.com/Cologler/PSLazyCompletion.

However, it cannot support `scoop-completion` since `scoop-completion` does not use `Register-ArgumentCompleter` to add the completer.

Ref with #20.

**Comment by Moeologist** [comment]
Fixed on v0.3.0
