### ISSUE TITLE
It has no effect on the package name. Whether it is install or uninstall followed by package name completion, it cannot be used.

### ISSUE THREAD

**Issue by tianlongJ** [liuzijing97/scoop-auto-completion#33]

**Comment by Lockszmith-GH** [comment]
It works for me, so if possible, can you please provide a bit more infrmation which might help understand why things aren't working for you?

Are you in PowerShell?

After you installed the scoop-completion with `scoop install scoop-completion` did you run the `import-module` as described in the (README)[https://github.com/Moeologist/scoop-completion#scoop-completion]?

```ps1
# enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
```

PowerShell TabExpansion relies on a module named PSReadLine, is it installed?

Please provide the output of the following commands:
```
$PSVersionTable
Get-Modules
```

This information should be helpful in pin pointing possible cause.

**Comment by tianlongJ** [comment]
> It works for me, so if possible, can you please provide a bit more infrmation which might help understand why things aren't working for you?
> 
> Are you in PowerShell?
> 
> After you installed the scoop-completion with `scoop install scoop-completion` did you run the `import-module` as described in the (README)[https://github.com/Moeologist/scoop-completion#scoop-completion]?
> 
> ```powershell
> # enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
> Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> ```
> 
> PowerShell TabExpansion relies on a module named PSReadLine, is it installed?
> 
> Please provide the output of the following commands:
> 
> ```
> $PSVersionTable
> Get-Modules
> ```
> 
> This information should be helpful in pin pointing possible cause.

Enter scoop install oraclej and press tab, expecting the completion to be scoop install oraclejdk, but it does not happen, and nothing happens when using ctrl+space.
![image](https://github.com/Moeologist/scoop-completion/assets/50390874/f8937ec9-d7ad-402e-a71a-28674f1e21dc)

**Comment by Moeologist** [comment]
> > It works for me, so if possible, can you please provide a bit more infrmation which might help understand why things aren't working for you?
> > Are you in PowerShell?
> > After you installed the scoop-completion with `scoop install scoop-completion` did you run the `import-module` as described in the (README)[https://github.com/Moeologist/scoop-completion#scoop-completion]?
> > ```powershell
> > # enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
> > Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PowerShell TabExpansion relies on a module named PSReadLine, is it installed?
> > Please provide the output of the following commands:
> > ```
> > $PSVersionTable
> > Get-Modules
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This information should be helpful in pin pointing possible cause.
> 
> Enter scoop install oraclej and press tab, expecting the completion to be scoop install oraclejdk, but it does not happen, and nothing happens when using ctrl+space. ![image](https://user-images.githubusercontent.com/50390874/278847732-f8937ec9-d7ad-402e-a71a-28674f1e21dc.png)

Run Get-PSReadLineKeyHandler and check output , check Windows Terminal key binding. Tab completion maybe conflict with other hotkey

**Comment by tianlongJ** [comment]
> > > 它对我有用，所以如果可能的话，你能提供更多的信息，这可能有助于理解为什么事情对你不起作用吗？你在 PowerShell 中吗？安装 scoop-completion 后，您是否按照 （README）[https://github.com/Moeologist/scoop-completion#scoop-completion] 中的描述运行？`scoop install scoop-completion``import-module`
> > > ```powershell
> > > # enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
> > > Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > PowerShell TabExpansion 依赖于名为 PSReadLine 的模块，是否已安装？请提供以下命令的输出：
> > > ```
> > > $PSVersionTable
> > > Get-Modules
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 此信息应有助于查明可能的原因。
> > 
> > 
> > 输入 scoop install oraclej 并按 tab，期望完成为 scoop install oraclejdk，但它不会发生，并且在使用 ctrl+space 时没有任何反应。![图像](https://user-images.githubusercontent.com/50390874/278847732-f8937ec9-d7ad-402e-a71a-28674f1e21dc.png)
> 
> 运行 Get-PSReadLineKeyHandler 并检查输出，检查 Windows 终端键绑定。Tab 自动补全可能与其他热键冲突



> > > It works for me, so if possible, can you please provide a bit more infrmation which might help understand why things aren't working for you?
> > > Are you in PowerShell?
> > > After you installed the scoop-completion with `scoop install scoop-completion` did you run the `import-module` as described in the (README)[https://github.com/Moeologist/scoop-completion#scoop-completion]?
> > > ```powershell
> > > # enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
> > > Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > PowerShell TabExpansion relies on a module named PSReadLine, is it installed?
> > > Please provide the output of the following commands:
> > > ```
> > > $PSVersionTable
> > > Get-Modules
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This information should be helpful in pin pointing possible cause.
> > 
> > 
> > Enter scoop install oraclej and press tab, expecting the completion to be scoop install oraclejdk, but it does not happen, and nothing happens when using ctrl+space. ![image](https://user-images.githubusercontent.com/50390874/278847732-f8937ec9-d7ad-402e-a71a-28674f1e21dc.png)
> 
> Run Get-PSReadLineKeyHandler and check output , check Windows Terminal key binding. Tab completion maybe conflict with other hotkey

The tab is not occupied. It can complete the history records in powershell or searchable files, but it cannot be completed.like this,When I use tab, the completion is the file under the environment variable path configuration, not the scoop command itself.
![image](https://github.com/Moeologist/scoop-completion/assets/50390874/93c3b712-a9a3-47a3-becd-0a1c7571b8c9)
![image](https://github.com/Moeologist/scoop-completion/assets/50390874/8f0dbeb2-f7db-4ede-88f2-b3839c2917ef)

**Comment by tianlongJ** [comment]
> ```powershell
> Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> ```

I know, the bucket path is fixed in the user directory, and I installed scoop in c:\Scoop, so all functions are disabled. I think I am not the only one who does not install scoop in the user directory.
![image](https://github.com/Moeologist/scoop-completion/assets/50390874/2f2cead6-7834-4252-bf57-333682772d66)

**Comment by tianlongJ** [comment]
> > > It works for me, so if possible, can you please provide a bit more infrmation which might help understand why things aren't working for you?
> > > Are you in PowerShell?
> > > After you installed the scoop-completion with `scoop install scoop-completion` did you run the `import-module` as described in the (README)[https://github.com/Moeologist/scoop-completion#scoop-completion]?
> > > ```powershell
> > > # enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
> > > Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > PowerShell TabExpansion relies on a module named PSReadLine, is it installed?
> > > Please provide the output of the following commands:
> > > ```
> > > $PSVersionTable
> > > Get-Modules
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This information should be helpful in pin pointing possible cause.
> > 
> > 
> > Enter scoop install oraclej and press tab, expecting the completion to be scoop install oraclejdk, but it does not happen, and nothing happens when using ctrl+space. ![image](https://user-images.githubusercontent.com/50390874/278847732-f8937ec9-d7ad-402e-a71a-28674f1e21dc.png)
> 
> Run Get-PSReadLineKeyHandler and check output , check Windows Terminal key binding. Tab completion maybe conflict with other hotkey

I know, the bucket path is fixed in the user directory, and I installed scoop in c:\Scoop, so all functions are disabled. I think I am not the only one who does not install scoop in the user directory.
![image](https://github.com/Moeologist/scoop-completion/assets/50390874/a5b04541-22e8-455e-8102-77e9b73b29a8)

**Comment by tianlongJ** [comment]
> > > It works for me, so if possible, can you please provide a bit more infrmation which might help understand why things aren't working for you?
> > > Are you in PowerShell?
> > > After you installed the scoop-completion with `scoop install scoop-completion` did you run the `import-module` as described in the (README)[https://github.com/Moeologist/scoop-completion#scoop-completion]?
> > > ```powershell
> > > # enable completion in current shell, use absolute path because PowerShell Core not respect $env:PSModulePath
> > > Import-Module "$($(Get-Item $(Get-Command scoop.ps1).Path).Directory.Parent.FullName)\modules\scoop-completion"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > PowerShell TabExpansion relies on a module named PSReadLine, is it installed?
> > > Please provide the output of the following commands:
> > > ```
> > > $PSVersionTable
> > > Get-Modules
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This information should be helpful in pin pointing possible cause.
> > 
> > 
> > Enter scoop install oraclej and press tab, expecting the completion to be scoop install oraclejdk, but it does not happen, and nothing happens when using ctrl+space. ![image](https://user-images.githubusercontent.com/50390874/278847732-f8937ec9-d7ad-402e-a71a-28674f1e21dc.png)
> 
> Run Get-PSReadLineKeyHandler and check output , check Windows Terminal key binding. Tab completion maybe conflict with other hotkey

I know the reason, it was unclear to me why I didn't have SCOOP in my environment variables but USERSCOOP and now it works
