### ISSUE TITLE
Provide scoop-auto-completion through scoop

### ISSUE THREAD

**Issue by Lockszmith-GH** [liuzijing97/scoop-auto-completion#4]
Seems that a scoop enhancement as excellent as this, should be available via scoop.
Is there a reason not to implement this?

BTW: Thanks for making this!

**Comment by Moeologist** [comment]
You mean that provide this function via scoop itself? Or provide a scoop bucket?
Few people use shell completion. Additional config is necessary, even integrating this to scoop.
For the latter, PSGallery is available.

**Comment by Lockszmith-GH** [comment]
I meant a bucket.
scoop install scoop-auto-complete

Make it a part of the scoop ecosystem.

**Comment by Moeologist** [comment]
solved

**Comment by Lockszmith-GH** [comment]
I never thanked you for this, this is beyond awesome!

This has become part of my staple-installation:
```powershell
# Add scoop-completion bucket, followed by installation
scoop bucket add scoop-completion 'https://github.com/Moeologist/scoop-completion'
scoop install scoop-completion

# Add alias for easy invocation (should also work in Pwsh)
scoop alias add autocomplete-on  'Get-Module -ListAvailable $env:SCOOP\modules\* | Where-Object Name -eq scoop-completion | Import-Module'
scoop alias add autocomplete-off 'Get-Module scoop-completion | Remove-Module'

# Activate scoop-autocomplete
scoop autocomplete-on
```

You are welcome to checkout my [full installation script](https://code.lksz.me/lksz/szcoop/src/branch/master/FreshInstall.ps1).
THANK YOU!

###### EDIT: changed liuzijing97 to Moeologist in URL

**Comment by TheWiresharkGuy** [comment]
@Lockszmith 

Hi !

The link to your full installation script gives me a 404 error :(

**Comment by Lockszmith-GH** [comment]
@TheWiresharkGuy please try again, for some reason my server was down, it's back up.

**Comment by TheWiresharkGuy** [comment]
@Lockszmith Thank you for your awsome script ! 👍
