### ISSUE TITLE
Installation method for powershell and pwsh differ

### ISSUE THREAD

**Issue by matthewbegun** [liuzijing97/scoop-auto-completion#7]
The listed methods for installing in (windows) powershell and (core) pwsh differ and produce errors when used by each other. 

If we share the PowerShell_profile.ps1 file for both versions this is an issue.

Can replace both methods with the following code which works either way, and doesn't produce any errors in either version:

```
# enable auto-load, create profile if not exist
$env:SCOOP = "$env:USERPROFILE\scoop"; Add-Content -Path $Profile -Value "`nImport-Module $env:SCOOP/modules/scoop-completion"
```

**Comment by Moeologist** [comment]
The method for PS Core seems to be well in Windows PS. On the contrary, it is not. 
Anyway I modified README.
