### ISSUE TITLE
Missing hash

### ISSUE THREAD

**Issue by SonOfDiablo** [liuzijing97/scoop-auto-completion#9]
Would it be possible for you to include the file hash for master.zip in the manifest?

**Comment by Moeologist** [comment]
Hash zip file is possiable. If I modified the manifest（add hash）, the zip file hash would be changed at the same time. It is necessary to download manifest and ps module separately. Any idea? [scoop wiki](https://github.com/lukesampson/scoop/wiki/App-Manifests)
